### ISSUE TITLE
{"statusCode":500,"message":"Internal server error"}

### ISSUE THREAD

**Issue by spinnaker1** [yashha/percollate-api#3]
I tried deploy it on heroku (free account), but I get the error message "{"statusCode":500,"message":"Internal server error"}" when it click:
https://xyzmyapp.herokuapp.com/pdf?url=https://de.wikipedia.org/wiki/JavaScript

I copied your repository as a private repo to my github account and used it in heroku to deploy it. I didnt change anything, so Im wondering why it gives the error message.

Please help me, because this is absolutely amazing!

**Comment by yashha** [comment]
You need following build packs:
heroku/nodejs
https://github.com/jontewks/puppeteer-heroku-buildpack

**Comment by spinnaker1** [comment]
Thanks, now it works.
