### ISSUE TITLE
Request: Docker container

### ISSUE THREAD

**Issue by spinnaker1** [yashha/percollate-api#4]
If it's possible, a docker container would be interesting. 

Percollate is really the only tool (I know of) to create beautiful looking pdfs from webpages. A docker image would be a real benefit also to docker hub community.

**Comment by yashha** [comment]
#4 @spinnaker1 What do you think?

**Comment by yashha** [comment]
Did you mean a docker image for the cli or the api?

**Comment by spinnaker1** [comment]
> Did you mean a docker image for the cli or the api?

For this repository, percollate-api. It's ideal with its API function to run in a docker container and serve requests:
`localhost:3000/pdf?url=http://example.com&css=@page%20{%20size:%20A4%20portrait%20}`

---------------------------------------------
I tried the dockerfile and it successfully built online on docker.com (i tried in a private, non public repository). But when I run the container, it exists with an error:

`sudo docker run -p 3000:3000 mydockerusername/percollate-api` 
```
> percollate-api@1.0.0 start /app
> node dist/src/main.js

internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '/app/dist/src/main.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! percollate-api@1.0.0 start: `node dist/src/main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the percollate-api@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-13T12_45_15_859Z-debug.log

```

But if the container worked for you, please publish it on hub.docker.com, with a hint on how to properly start it and how to properly invoke it.

**Comment by yashha** [comment]
Yes sry I didn't test it, it seems i have to correct it

**Comment by yashha** [comment]
https://hub.docker.com/r/yashha/percollate-api

**Comment by yashha** [comment]
To run:
docker run -it -p 3000:3000 <image>:<tag>
