### ISSUE TITLE
Request: Automatically name the pdf file after article headline

### ISSUE THREAD

**Issue by spinnaker1** [yashha/percollate-api#8]
Currently the pdf output file is named `pdf.pdf`.

**Is it possible to automatically name the pdf file after the article headline?**

Interesstingly in the exif data of the pdf file, the `title` of the article is correctly inserted.
I use `wget` and `percollate-api` to batch download thousands of articles and afterwards use `exiftool '-filename<$title.%e' *.pdf` to manually batch rename all pdfs after their title.

_Hint: Interesstingly percollate-api is twice as fast as percollate cli on my plattform. Awesome._

**Comment by yashha** [comment]
Update here 06e34c534cb3e21775dc8769da337c95d0cc1050

You can now use the content-disposition flag:
`wget --content-disposition https://percollate-api.herokuapp.com/pdf\?url\=https://de.wikipedia.org/wiki/JavaScript`

Does this work for you?

**Comment by spinnaker1** [comment]
> Does this work for you?
Yes, it works. 🥇 👍
